### ISSUE TITLE
feature request: Matrix support

### ISSUE THREAD

**Issue by koyuawsmbrtn** [revoltchat/backend#194]
### What do you want to see?

Hear me out, if you can't implement Matrix on your own you're free to get help from the Matrix community. Having a proper alternative to the Synapse/Element ecosystem would make Matrix a thousand times better.

**Comment by Rexogamer** [comment]
Revolt is its own platform and we have no current plans to turn it into an alternative implementation of the Matrix protocol - we may, however, add support for bridging Matrix rooms to Revolt channels in the future.

**Comment by koyuawsmbrtn** [comment]
And this is what I thought you'd do. Discuss it or hand the project to a more competent maintainer.

**Comment by b1ue64** [comment]
> And this is what I thought you'd do. Discuss it or hand the project to a more competent maintainer.

What the hell is wrong with a non-Matrix chat platform?

**Comment by koyuawsmbrtn** [comment]
> > And this is what I thought you'd do. Discuss it or hand the project to a more competent maintainer.
> 
> What the hell is wrong with a non-Matrix chat platform?

I don't know, but having a non-encrypted centralised platform usually means that you have to trust the maintainer which is usually not the case if you're a sane person

**Comment by b1ue64** [comment]
> > > And this is what I thought you'd do. Discuss it or hand the project to a more competent maintainer.
> > 
> > 
> > What the hell is wrong with a non-Matrix chat platform?
> 
> I don't know, but having a non-encrypted centralised platform usually means that you have to trust the maintainer which is usually not the case if you're a sane person

There are plans for encrypted DMs, and adding encrypted servers after the fact would be extremely hard.
Also, you're using a centralized platform right now. If you're this opposed to centralized platforms, maybe don't use GitHub.

**Comment by insertish** [comment]
> And this is what I thought you'd do. Discuss it or hand the project to a more competent maintainer.

Please respect our code of conduct while you're here, Rexo gave a perfectly fine explanation.

Revolt is an entirely independent protocol, making it  work with Matrix is basically a whole project in it of itself and it's not something I'm interested in doing.

People keep saying that others can help or we can get help from certain people but nobody steps up for these sorts of huge feats, I continue to be the only person accounting for the majority of the work done here.

**Comment by viasux** [comment]
> > > > And this is what I thought you'd do. Discuss it or hand the project to a more competent maintainer.
> > > 
> > > 
> > > What the hell is wrong with a non-Matrix chat platform?
> > 
> > 
> > I don't know, but having a non-encrypted centralised platform usually means that you have to trust the maintainer which is usually not the case if you're a sane person
> 
> There are plans for encrypted DMs, and adding encrypted servers after the fact would be extremely hard. Also, you're using a centralized platform right now. If you're this opposed to centralized platforms, maybe don't use GitHub or Twitch.

OP is being an asshole, but there's validity to some of the things they're saying. Matrix is superior in the sense that speech *cannot* be censored by a central authority. E2EE is not enough, when corporations and malicious individuals have control over the server running the program itself. We need spaces where we can communicate freely without the threat of censorship, from both a company/organization taking down chats, and prejudiced governments.

I don't understand why there's a need to make a new backend, instead of just adhering to the matrix spec, enabling more accessibility, security, and interoperability.

Creating something new (and less functional), just splits up the dev time and work for no discernible reason. The frontend for revolt is great, but the backend is irrelevant because it can easily be censored or taken down.
